### ISSUE TITLE
Spawner Modification Crash

### ISSUE THREAD

**Issue by AlmanaX-21** [mineblock11/Zenith#9]
While building a small modpack, modifying spawner obtained through the `/give AlmanaX21 minecraft:spawner` causes the game to crash completely, tried using a comparator first and then a spawn egg both crashed the game.

**Zenith Version: zenith-0.4.3+1.19.2.jar**
**Fabric Version: 0.14.13**

I'll provide the modlist if necessary.

**Comment by AlmanaX-21** [comment]
Crash Error:
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-02-07 12:00:28
Description: Unexpected error

java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.sort(ImmutableCollections.java:261)
	at safro.zenith.spawn.modifiers.SpawnerModifier.findMatch(SpawnerModifier.java:132)
	at net.minecraft.class_2496.method_9534(class_2496.java:1067)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1748)
	at net.minecraft.class_310.method_1508(class_310.java:2002)
	at net.minecraft.class_310.method_1574(class_310.java:1829)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.sort(ImmutableCollections.java:261)
	at safro.zenith.spawn.modifiers.SpawnerModifier.findMatch(SpawnerModifier.java:132)
	at net.minecraft.class_2496.method_9534(class_2496.java:1067)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1748)
	at net.minecraft.class_310.method_1508(class_310.java:2002)

-- Affected level --
Details:
	All players: 1 total; [class_746['AlmanaX21'/315, l='ClientLevel', x=97.55, y=48.00, z=105.50]]
	Chunk stats: 1024, 240
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,71,144), Section: (at 0,7,0 in 7,4,9; chunk contains blocks 112,-64,144 to 127,319,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 401018 game time, 490883 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (x86_64) version 10.15.7
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 999539896 bytes (953 MiB) / 2279604224 bytes (2174 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel HD Graphics 4000
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x0166
	Graphics card #0 versionInfo: Revision ID: 0x0009
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 5120.00
	Virtual memory used (MB): 3317.20
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 607.50
	JVM Flags: 3 total; -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advancednetherite: Advanced Netherite 1.6.6-1.19.2
		almostunified: AlmostUnified 1.19.2-0.3.4
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.4.62
		attributefix: AttributeFix 17.1.3
		badpackets: Bad Packets 0.2.1
		bookshelf: Bookshelf 16.2.17
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cleancut: CleanCut 1.19.2-5.1-fabric
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		cobblegen: CobbleGen v2.1b57-BETA
			blue_endless_jankson: jankson 1.2.1
		collective: Collective 6.43
		controlling: Controlling For Fabric 10.0+7
		create: Create 0.5.0.i-925+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.8.a-4
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.731+1.19.2
				com_github_llamalad7_mixinextras: MixinExtras 0.1.1
				forge_tags: Porting Lib Tags 3.0
				mm: Manningham Mills 2.3
				porting_lib_accessors: Porting Lib Accessors 2.1.731+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.731+1.19.2
				porting_lib_base: Porting Lib Base 2.1.731+1.19.2
				porting_lib_common: Porting Lib Common 2.1.731+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.731+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.731+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.731+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.731+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.731+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.731+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.731+1.19.2
				porting_lib_models: Porting Lib Models 2.1.731+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.731+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.731+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.731+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.50-MC1.19.2
		createchunkloading: Create Chunkloading 1.3.0
		dankstorage: Dank Storage 1.19.2-4.3
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		easymagic: Easy Magic 4.3.2
		enchdesc: EnchantmentDescriptions 13.0.14
		enderchests: EnderChests 1.1.1
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
		fabric-api: Fabric API 0.73.2+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.24+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.1+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.13
		ferritecore: FerriteCore 5.0.3
		forgeconfigapiport: Forge Config API Port 4.2.10
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		ftblibrary: FTB Library 1902.3.11-build.166
		ftbultimine: FTB Ultimine 1902.3.5-build.65
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		gammautils: Gamma Utils 1.6.10
		gobber2: Gobber2 2.6.61
			pugh_lib: Pugh Lib 1.4.15
			pugh_tools: Pugh Tools 1.3.23
		indium: Indium 1.0.9+mc1.19.2
		ironchests: Iron Chests: Restocked 3.1.1
			resourcefullib: Resourceful Lib 1.1.15
		jade: Jade 8.7.3
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		leavesbegone: Leaves Be Gone 4.0.1
		lithium: Lithium 0.10.4
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		owo: oωo 0.8.5+1.19
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pickablevillagers: Pickable Villagers 1.3.4+1.19.2
		pigpen: PigPen 11.1.2
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		roughlyenoughitems: Roughly Enough Items 9.1.587
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		shetiphiancore: ShetiPhianCore 1.3.4
		slotlink: slotlink 5.0.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		squatgrow: Squat Grow 3.0.0-build.33+mc1.19.2
		starlight: Starlight 1.1.1+fabric.ae22326
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.12
		trinkets: Trinkets 3.4.2
		villagespawnpoint: Village Spawn Point 4.0
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yigd: You're in Grave Danger 1.4.8
		zenith: Zenith 0.4.3+1.19.2
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.13-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel HD Graphics 4000 OpenGL Engine GL version 4.1 INTEL-14.7.26, Intel Inc.
	Window size: 1280x800
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['AlmanaX21'/315, l='ServerLevel[New World]', x=97.55, y=48.00, z=105.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
```
